### PR TITLE
added package.json and instructions how to run

### PR DESCRIPTION
**Pull request by DJCordhose**
To make it more self contained (no global installs, just npm install)

### CODE REVIEW

**Comment by rauschma** [comment]
Good idea! A few suggestions:
- Change the name of the webpack script from `dev` to `watch`. That’ll leave room for other dev-related names such as `compile` and `test`.
- IIRC, `"webpack --watch"` is enough, because npm sets up the $PATH correctly (no need to use a relative path).
- I’d use `"*"` for the versions (vs. `"^5.7.4"` etc.)

What do you think?

**Comment by rauschma** [comment]
For the README, I’d use a bullet list and would not mention `open index.html` (which is an OS X specific command).

**Comment by DJCordhose** [comment]
- Readme updated
- `*` for versions already used in 645687c
- `dev` changed to `watch`
- npm script makes global installation of webpack obsolete - original motivation for this pull request :)

**Comment by rauschma** [comment]
- npm script temporarily adds `./node_modules/.bin/` to the $PATH (I think). Thus, you probably don’t need the relative path.
- `new webpack.NoErrorsPlugin()` is new – add a comment explaining why it’s there?

**Comment by rauschma** [comment]
You can check whether the npm script works correctly if you temporarily rename the script in `./node_modules/.bin/` (e.g. to `webpack2`) and call that script.

**Comment by DJCordhose** [comment]
Both points valid - addressed in 4f67f1a! Did not know about the script path when running npm script - thanks :)

**Comment by rauschma** [comment]
Yeah, being able to run local scripts like this is really cool.

**Comment by DJCordhose** [comment]
:+1:

**Pull request merged**
